### ISSUE TITLE
Support for Additional Latex Package Chemfig.

### ISSUE THREAD

**Issue by ajeducation** [ethan-ou/vscode-gift-pack#1]
We use LATEX package 'Chemfig' to add Organic Chemistry Structures in Moodle. Is there a way to add additional LATEX package so that output can be viewed in preview window?

**Comment by ethan-ou** [comment]
To display LaTeX I'm using a package called KaTeX. They've [opened an issue](https://github.com/KaTeX/KaTeX/issues/2232) to talk about how to port chemfig but apparently it's a pretty complex problem and no substantial progress has been made. If you're ever up for a challenge, you can try to give it a shot!

The other thing you can try is injecting SVG directly into the GIFT question. Once you've written something in chemfig, take the SVG output (should look like HTML) and copy it over to your question. Make sure you also escape everything so that it displays properly in GIFT. You can do this quickly by selecting the SVG text, then right clicking and going to Refactor > Escape Text.

**Comment by ajeducation** [comment]
I had earlier tried placing SVG in html editors of Moodle, but that did not work. Additionally SVG is not neat because it contain larger code than chemfig. I have enabled chemfig in Moodle and it works fine. In our academic college, I will  teach the teachers about Moodle GIFT format. I will use your VSCode-gift pack for same, Its snippets and preview mode is really useful for new learners.  I understand from you that there is no easy solution to preview chemfig in VSCode-gift-pack, so its ok if chemfig can not be previewed.  
**mhchem** is another extension for chemistry in LaTeX and [KaTeX non-natively support it ](https://github.com/KaTeX/KaTeX/tree/master/contrib/mhchem). How **mhchem** can be enabled in VSCode-gift-pack?

**Comment by ethan-ou** [comment]
mhchem definitely looks doable. Let me open this back up and I'll give it a shot at integrating it.

**Comment by ethan-ou** [comment]
mhchem is working perfectly. The update should go live as soon as you read this.

![image](https://user-images.githubusercontent.com/45083970/107642717-5aa63380-6cc9-11eb-9ff7-4b9fa06a2d87.png)

**Comment by ajeducation** [comment]
**Thanks** for mhchem update.  Is it possible to implement LaTeX support **without escaping curly brackets.** In LaTeX and Moodle, curly brackets will be used as such without escape character. Meanwhile  workaround will be to to find and replace escaped brackets and then import into Moodle.

**Comment by ethan-ou** [comment]
Are you sure this is the case with LaTeX in GIFT? Would you be able to show me what happens when escaped vs unescaped GIFT questions are uploaded to Moodle?

**Comment by ajeducation** [comment]
You are right. In Moodle, While uploading from GIFT format, reserve characters need to be escaped, while writing directly on Moodle interface, reserve characters are not escaped.

**Comment by ethan-ou** [comment]
Good to hear! I'll close this for now. Let me know if you find any solutions for implementing chemfig with KaTeX and we'll open it back up.
